.TH "GTOP" "1" "January 2022" "v1.1.2" "Gtop Help"
.SH "NAME"
\fBGTOP\fR
.QP
.P
gtop \- System monitoring dashboard for terminal

.
.SH SYNOPSIS
.P
\fBgtop\fP
.SH DESCRIPTION
.P
gtop is a system monitoring dashboard for terminal much like htop, top, etc\.\.\.
.SH INTERACTIVE COMMANDS
.P
The following commands are supported while in gtop:
.RS 0
.IP \(bu 2
\fBp\fP sort the process table by Process Id
.IP \(bu 2
\fBc\fP sort the process table by CPU usage
.IP \(bu 2
\fBm\fP sort the process table by Memory usage

.RE
.SH Website
.P
https://github\.com/aksakalli/gtop \fIhttps://github\.com/aksakalli/gtop\fR
.SH BUGS
.P
Please report any bugs to https://github\.com/aksakalli/gtop\.
.SH LICENSE
.P
Copyright (c) 2017, Can Güney Aksakalli (MIT License)\.
.SH SEE ALSO
.P
node\.js(1),

