name: gtop
summary: System monitoring dashboard for terminal
description: |
  System monitoring dashboard for terminal
version: v1.1.5
base: core22
grade: stable

confinement: classic

apps:
  gtop:
    command: bin/gtop

parts:
  gtop:
    source: https://github.com/aksakalli/gtop.git
    source-tag: ${SNAPCRAFT_PROJECT_VERSION}
    plugin: npm
    npm-include-node: true
    npm-node-version: "17.3.0"
