name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint check
        run: npm run lint-check
      - name: Test
        run: npm test
